output$qaqcSiteStationSelects <- renderUI({
  
  div(
    selectInput('qaqcSiteSelect', "Select Site", unique(goop$combined_df$Site)),
    selectInput('qaqcStationSelect', 'Select Station', unique(goop$combined_df$Station))
  )
})

observeEvent(input$qaqcSave, {
  file_path <- PROCESSED_FOLDER
  file_name <- "output.csv"
  
  for(site in unique(goop$combined_df$Site)){
    for(station in unique(goop$combined_df$Station)){
      date <- str_split(min(goop$combined_df$Date_Time), pattern = ' ')[[1]][1]
      file_name <- paste0('processed_',site,'_',station,'_',date,'.csv')
      exportDF <- goop$combined_df
      exportDF['Date_Time'] <- format(exportDF['Date_Time'], "%m/%d/%y %I:%M:%S %p")
      write.csv(exportDF, file_name, row.names = FALSE)
      drive_upload(name = file_name, media = file_name, path = file_path)
      file.remove(file_name)
    }
  }
  alert('Files Uploaded!')
})


observeEvent(input$uploadBtn, {
  output$varContainers <- renderUI({
    vars <- unique(goop$combined_df$Variable)
    LL <- vector("list",length(vars))       
    for(i in vars){
      LL[[i]] <- list(varContainerUI(id = i, var = i))
    }      
    return(LL)  
  }) #when user clicks on upload button, the code generates a dynamic UI called varContainers that contains UI elements generated by the varContainerUI function for each unique variable in the goop$combined_df data frame.
  
  observe({
    lapply(unique(goop$combined_df$Variable), function(i) {
      varContainerServer(id = i, 
                         variable = i, 
                         goop = goop, 
                         dateRange = reactive({input$date_range_qaqc}),
                         pickedSite = reactive({input$qaqcSiteSelect}),
                         pickedStation = reactive({input$qaqcStationSelect}))
    })
  }) # continuously observes changes in the unique variables present in the goop$combined_df data frame.
}) #based on data uploaded, variables and dataframe changes

output$qaqcDateRange <- renderUI({
  start_date = min(goop$combined_df$Date_Time)
  end_date = max(goop$combined_df$Date_Time)
  dateRangeInput("date_range_qaqc", "Select Date(s) To View/Calculate",
                 start = start_date, end = end_date, min = start_date, max = end_date)
})

