---
title: "weatherMarkdown"
output: html_document
date: "2023-07-27"
---

```{r setup, include=FALSE}
library(httr)
library(jsonlite)
library(tidyverse)
library(gridExtra)
```


```{r setup, include=FALSE}
res = GET("https://archive-api.open-meteo.com/v1/archive?latitude=35.980472&longitude=-79.004672&start_date=2023-02-20&end_date=2023-03-06&hourly=temperature_2m,relativehumidity_2m,rain,snowfall,cloudcover,windspeed_10m,is_day,direct_radiation&timezone=America%2FNew_York&models=best_match")

data = as.data.frame(fromJSON(rawToChar(res$content)))
```


```{r setup, include=FALSE}
print(names(data))
```


```{r setup, include=FALSE}

df <- read.csv("gas_app/NC_NHC_2023-03-06_HD.csv", header = F)
df  <- df[-c(1,2),c(1,2,3,4)]
colnames(df) <- c("id", "Date_Time", "DO", "Temp_C")
df <- df[df$DO != '',]
View(df)
```


```{r}
new_df = df
new_data = data[18:348,]
new_data = new_data[rep(seq_len(nrow(new_data)), each = 4), ]
new_data = new_data[0:1322,]
colnames(new_df) <- c("number", "date", "DO", "Temp")
new_df <- new_df[new_df$DO != '',]
DO = as.numeric(new_df$DO)
new_df$DO = DO
Time = new_df$date
Time = strsplit(Time, " ")
Ex_Time <- c()
for(i in 1:length(Time)){
  AM_PM = Time[[i]][3]
  Temp_Time = strsplit(Time[[i]][2], ":")
  H = as.numeric(Temp_Time[[1]][1])
  M = as.numeric(Temp_Time[[1]][2])
  S = as.numeric(Temp_Time[[1]][3])
  if(H == 12){
    H = H - 12
  }
  if(AM_PM=="PM")
    H = H + 12
  Ex_Time[i] = 60*H + M + S/60
}
plot(Ex_Time, DO)
new_df$Time = Ex_Time
```


```{r}
day = c(rep(1,28))
for(i in 2:14){
 day = c(day, rep(i,96)) 
}
day = c(day,rep(14,46))
combined_df = cbind(new_df, new_data)
combined_df$Temp = as.numeric(combined_df$Temp)
combined_df = combined_df[,c(3:5,23:25,27:30)]
combined_df$hourly.is_day = as.factor(combined_df$hourly.is_day)
combined_df$day = as.factor(day)
train_index = c(1:499,600:1322)
train_df = combined_df[train_index,]
test_df = combined_df[-train_index,]
p1 <- ggplot()+
  geom_point(aes(x = train_df$Time, y = train_df$DO), color='grey')+
  geom_point(aes(x = test_df$Time, y = test_df$DO), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("original")
p1
```

```{r}
library("DMwR2")
combined_df[c(500:600),'DO'] <- NA
filled_df <- knnImputation(combined_df[c(1:3,9,11)])
p2 <- ggplot()+
  geom_point(aes(x = filled_df$Time[-c(500:600)], y = filled_df$DO[-c(500:600)]), color='grey')+
  geom_point(aes(x = filled_df$Time[c(500:600)], y = filled_df$DO[c(500:600)]), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("KNN")
p2
```
```{r}
temp_DO <- test_df$DO
test_df$DO <- NA
fit1 <- lm(DO ~ Time+Temp+day+hourly.is_day, data = train_df)
pred1 <- predict(fit1, newdata = test_df)
p3 <- ggplot()+
  geom_point(aes(x = train_df$Time, y = train_df$DO), color="grey")+
  geom_point(aes(x = test_df$Time, y = pred1), color="red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("Linear Regression")
p3
```
```{r}
mean_rep = train_df %>% 
  group_by(Time) %>%
  summarise(mean_DO = mean(DO))
pred2 <- c()
for(i in 1:100){
  pred_Time = test_df$Time[i]
  pred2[i] <- mean_rep[mean_rep$Time==pred_Time,]$mean_DO
}
p4 <- ggplot()+
  geom_point(aes(x = train_df$Time, y = train_df$DO), color='grey')+
  geom_point(aes(x = test_df$Time, y = pred2), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("Mean")
p4
```
```{r,fig.width=8,fig.height=6}
test_df$DO = DO[500:599]
grid.arrange(p1,p2,p3,p4,ncol=2)
```

