---
title: "Untitled"
author: "Yiliang Yuan"
date: "2023-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(lubridate)
```

```{r}
# load your own csv file containing DO and other variables
df <- read.csv("Test.csv")
```

```{r}
Time = df$date
Time = strsplit(Time, " ")
Ex_Time <- c()
date_index = c()
pre_date = strsplit(Time[[1]][1], split = "/")[[1]][2]
pre_index = 1
# convert time to time of a day
for(i in 1:length(Time)){
  AM_PM = Time[[i]][3]
  Temp_Time = strsplit(Time[[i]][2], ":")
  H = as.numeric(Temp_Time[[1]][1])
  M = as.numeric(Temp_Time[[1]][2])
  S = as.numeric(Temp_Time[[1]][3])
  if(H == 12){
    H = H - 12
  }
  if(AM_PM=="PM")
    H = H + 12
  Ex_Time[i] = 60*H + M + S/60
  if(strsplit(Time[[i]][1], split = "/")[[1]][2] == pre_date)
    date_index[i] = pre_index
  else{
    pre_index = pre_index+1
    date_index[i] = pre_index+1    
  }
  # add date index for different days
  pre_date = strsplit(Time[[i]][1], split = "/")[[1]][2]
}
plot(Ex_Time, df$DO)
df$Time = Ex_Time
df$date_index = date_index
```

```{r}
# leave only variables for prediction
missing_index = which(is.na(df$DO))
observed_df = df[-missing_index, 3:6]
missing_df = df[missing_index, 3:6]
p1 <- ggplot()+
  geom_point(aes(x = observed_df$Time, y = observed_df$DO), color='grey')+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("original")
p1
```


```{r}
fit1 <- lm(DO ~ .+I(Time^2), data = observed_df)
pred1 <- predict(fit1, newdata = missing_df)
p2 = ggplot()+
  geom_point(aes(x = observed_df$Time, y = observed_df$DO), color="grey")+
  geom_point(aes(x = missing_df$Time, y = pred1), color="red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("Regression for all")
p2
```

```{r}
mean_rep = observed_df %>% 
  group_by(Time) %>%
  summarise(mean_DO = mean(DO))
pred2 <- c()
for(i in 1:100){
  pred_Time = missing_df$Time[i]
  pred2[i] <- mean_rep[mean_rep$Time==pred_Time,]$mean_DO
}
p3 = ggplot()+
  geom_point(aes(x = observed_df$Time, y = observed_df$DO), color='grey')+
  geom_point(aes(x = missing_df$Time, y = pred2), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("Mean")
p3
```

```{r}
library("DMwR2")
filled_df <- knnImputation(df[,3:6])
p4 = ggplot()+
  geom_point(aes(x = filled_df$Time[-missing_index], y = filled_df$DO[-missing_index]), color='grey')+
  geom_point(aes(x = filled_df$Time[missing_index], y = filled_df$DO[missing_index]), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("KNN")
p4
```

```{r, fig.height=10, fig.width=12}
library(gridExtra)
library(grid)
grid.arrange(p2, p3, p4, ncol=2)
```

