---
title: "Untitled"
author: "Yiliang Yuan"
date: "2023-07-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(lubridate)
```

```{r}
df <- read.csv("ex_with_do_df.csv", header = F)
df  <- df[-c(1,2, 2701, 2702, 2703),c(1,2,3,4)]
colnames(df) <- c("number", "date", "DO", "Temp")
df <- df[df$DO != '',]
View(df)
```

```{r, fig.height=6}
par(mfrow=c(2,2))
DO = as.numeric(df$DO)
df$DO = DO

Temp = as.numeric(df$Temp)
plot(density(DO))
plot(density(log(DO)))
plot(density(Temp))
plot(Temp, DO)
```

```{r}
Time = df$date
Time = strsplit(Time, " ")
Ex_Time <- c()
for(i in 1:length(Time)){
  AM_PM = Time[[i]][3]
  Temp_Time = strsplit(Time[[i]][2], ":")
  H = as.numeric(Temp_Time[[1]][1])
  M = as.numeric(Temp_Time[[1]][2])
  S = as.numeric(Temp_Time[[1]][3])
  if(H == 12){
    H = H - 12
  }
  if(AM_PM=="PM")
    H = H + 12
  Ex_Time[i] = 60*H + M + S/60
}
plot(Ex_Time, DO)
df$Time = Ex_Time
```

```{r}
# manually delete some data
train_index = c(1:499,600:2698)
train_df = df[train_index, 3:5]
test_df = df[-train_index, 3:5]
p1 <- ggplot()+
  geom_point(aes(x = train_df$Time, y = train_df$DO), color='grey')+
  geom_point(aes(x = test_df$Time, y = test_df$DO), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("original")
p1
```


```{r}
temp_DO <- test_df$DO
test_df$DO <- NA
fit1 <- lm(DO ~ Time + I(Time^2), data = train_df)
pred1 <- predict(fit1, newdata = test_df)
p2 = ggplot()+
  geom_point(aes(x = train_df$Time, y = train_df$DO), color="grey")+
  geom_point(aes(x = test_df$Time, y = pred1), color="red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("Quadratic Regression")
p2
```

```{r}
mean_rep = train_df %>% 
  group_by(Time) %>%
  summarise(mean_DO = mean(DO))
pred2 <- c()
for(i in 1:100){
  pred_Time = test_df$Time[i]
  pred2[i] <- mean_rep[mean_rep$Time==pred_Time,]$mean_DO
}
p3 = ggplot()+
  geom_point(aes(x = df$Time, y = df$DO), color='grey')+
  geom_point(aes(x = test_df$Time, y = pred2), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("Mean")
p3
```

```{r}
library("DMwR2")
df_test <- df[,3:5]
df_test[c(500:600),'DO'] <- NA
filled_df <- knnImputation(df_test)
p4 = ggplot()+
  geom_point(aes(x = filled_df$Time[-c(200:300)], y = filled_df$DO[-c(200:300)]), color='grey')+
  geom_point(aes(x = filled_df$Time[c(200:300)], y = filled_df$DO[c(200:300)]), color = "red")+
  labs(x="Time in a day(Min)", y="DO")+
  ggtitle("KNN")
p4
```

```{r, fig.height=10, fig.width=12}
library(gridExtra)
library(grid)
test_df$DO <- temp_DO
grid.arrange(p1, p2, p3, p4, ncol=2)
```

